/**
 * Created by liapetronio on 12/24/14.
 */
// Generated by CoffeeScript 1.7.1
(function() {

    var margin = {t:100,r:150,b:250,l:150},
        margin2 = {t:30,b:100};
    width = $('.canvas').width() - margin.l - margin.r,
        height = $('.canvas').height() - margin.t - margin.b,
        height2 = margin.b - margin2.t - margin2.b;

    var svg = d3.select('.canvas')
        .append('svg')
        .attr('width', width + margin.l + margin.r)
        .attr('height', height + margin.t + margin.b)
        .append('g')
        .attr('transform',"translate("+margin.l+","+margin.t+")");


    var projection = d3.geo.mercator()
        .translate([width+900, height*4.5])
        .scale(700);


    var path = d3.geo.path()
        .projection(projection);

    var usTopoJson;
    var eventData;


//----------------------------------------------------------------------above is the global variable so that you can use it in multiple functions
    var y0 = 1979, y1=2012;

    var scales= {};
    scales.r = d3.scale.sqrt().domain([0, 70]).range([0,17]);
    scales.x = d3.scale.linear().domain([y0,y1]).range([0, width]);
    scales.y = d3.scale.linear().domain([0, 100]).range([height, 0]);


//----------------------------------------------------------------------
    $('.control #totalVictims').on('click', onClickTotalVictims);
//----------------------------------------------------------------------
    queue()

        .defer(d3.json, "data/us-10m.json")
        .defer(d3.csv, "data/MSA_Stanford_Complete_Database.csv", function(d){
            return {
                totalVictims: (+d["Total Number of Victims"] == " " ? undefined: +d["Total Number of Victims"]),
                kill: (+d["Number of Victim Fatalities"] == " " ? undefined: +d["Number of Victim Fatalities"]),
                wound: (+d["Number of Victims Injured"] == " " ? undefined: +d["Number of Victims Injured"]),
                id: +d["CaseID"],
                shooterAge: (+d["Average Shooter Age"] == " " ? undefined: +d["Average Shooter Age"]),
                shooterSex: (d["Shooter Sex"] == " " ? undefined: d["Shooter Sex"]),
                shooterRace: (d["Shooter Race"] == " " ? undefined: d["Shooter Race"]),
                typeOfGun: (d["Type of Gun – General"] == " " ? undefined: d["Type of Gun – General"]),
                numberOfGuns: (+d["Total Number of Guns"] == " " ? undefined: +d["Total Number of Guns"]),
                fateOfShooter: (d["Fate of Shooter"] == " " ? undefined: d["Fate of Shooter"]),
                mentalIllness: (d["History of Mental Illness - General"] == " " ? undefined: d["History of Mental Illness - General"]),
                schoolRelated: (d["School Related"] == " " ? undefined: d["School Related"]),
                placeType: (d["Place Type"] == " " ? undefined: d["Place Type"]),
                description: (d["Description"] == " " ? undefined: d["Description"]),
                date: +d.Date,
                lat: (+d["lat"] == " " ? undefined: +d["lat"]),
                lng: (+d["lng"] == " " ? undefined: +d["lng"]),
                lngLat: [+d["lng"], +d["lat"]]
            }
        })
        .await(dataLoaded);

//----------------------------------------------------------------------below is when i say the global = the parses data
    function dataLoaded(err, us, data) {
        if (err) console.error(err);

        usTopoJson = us;
        eventData = data;
        draw(eventData, usTopoJson);

    }

//----------------------------------------------------------------------
    function onClickTotalVictims(e){
        e.preventDefault();

        var circleNodes = svg.selectAll('circle')
            .transition()
            .attr('r', function(d){
                return scales.r(d.totalVictims)})
            .attr('opacity',.3)
            .style('fill', 'white')
    }


//--------------------------draw function--------------------------------------------this is my circles without any size or position so when ever i say "select all circles" it selects these and transforms them
    function draw(eventData, usTopoJson) {

        console.log(eventData);
        svg.append('path')
            .datum(topojson.mesh(usTopoJson, usTopoJson.objects.states))
            .attr('d', path)
            .attr('class', 'states')

        var circleNodes = svg.selectAll('.node')
            .data(eventData, function (d) {
                return d.id;
            })


        var circleNodesEnter = circleNodes.enter()
            .append('g')
            .attr('class', 'node')

        circleNodesEnter
            .append('circle')
            .attr('r', function(d){
                return scales.r(d.totalVictims)})
            .attr('transform', function(d){
                var xy = projection(d.lngLat);
                return 'translate(' + xy[0] + ',' + xy[1] + ')'; })
            .attr('opacity',.3)
            .style('fill', 'white')
            .attr('stroke-width',.5);

        circleNodes
            .exit()
            .remove();

    }



}).call(this);
